#!/usr/bin/env bash

DEVICE="$(ifconfig | grep -o -P "\b\w+(?=: flags=\d{1,4}<UP,BROADCAST)")"
DEVICE="$(echo $DEVICE | awk -F " " '{print $1}')"
# Check if there are devices running
if [[ ${#DEVICE} == 0 ]]; then exit 1; fi

STATUS=$(cat /sys/class/net/${DEVICE}/operstate)

URGENT_VALUE=20

if [[ "${STATUS}" == "up" ]]; then
  if [[ -d "/sys/class/net/${DEVICE}/wireless" ]]; then
    QUALITY=$(grep ${DEVICE} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    echo "${DEVICE} ${QUALITY}%"

    if [[ "${QUALITY}" -le "${URGENT_VALUE}" ]]; then
      exit 33
    fi
  else
    echo "${DEVICE} UP"
  fi
fi